### ISSUE TITLE
ValueError: '' is not in list

### ISSUE THREAD

**Issue by smilehacker-max** [FSecureLABS/GWTMap#6]
Whenever I provide --rpc flag it shows me this error.

![image](https://github.com/FSecureLABS/GWTMap/assets/30690468/a4fea8bb-bb9d-4895-ba98-e9a301f750fd)

**Comment by qgrosperrin** [comment]
Getting the same with Python3.12

**Comment by sysdefendr** [comment]
Having the same issue on Python3.

**Comment by osimonnet** [comment]
Seems to be resolved now
https://github.com/FSecureLABS/GWTMap/commit/1e921225b8fe32981c398d2bdcaf0c5561530cc3
